{"name": "失败用例1/0 会触发ZeroDivisionError", "status": "failed", "statusDetails": {"message": "Failed: DID NOT RAISE <class 'ZeroDivisionError'>", "trace": "self = <fixtureforassignments.testcase.test_calc.TestCalcuLator object at 0x7fcab5e2e6a0>\na = 1, b = 0, errorType = 'ZeroDivisionError'\ncalc_precedence = <fixtureforassignments.calculator.Calculator object at 0x7fcab5da12e0>\n\n    @allure.story('除法功能')\n    @allure.title('失败用例{a}/{b} 会触发{errorType}')\n    @pytest.mark.parametrize(**get_calc_data('div')['fail'])\n    def test_div_fail(self,a,b,errorType,calc_precedence):\n        with allure.step(f'计算{a}/{b}相除'):\n            logging.info(f'计算{a}/{b},预期结果为{errorType}异常')\n>       with pytest.raises(ZeroDivisionError,ValueError) as e:\nE       Failed: DID NOT RAISE <class 'ZeroDivisionError'>\n\ntest_calc.py:89: Failed"}, "steps": [{"name": "计算1/0相除", "status": "passed", "start": 1627228335360, "stop": 1627228335361}], "attachments": [{"name": "log", "source": "87030235-b7de-4e29-9928-7a3e6ff9134d-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "1"}, {"name": "b", "value": "0"}, {"name": "errorType", "value": "'ZeroDivisionError'"}], "start": 1627228335359, "stop": 1627228335361, "uuid": "2f0e0045-2ebf-4409-b113-97a9742207e2", "historyId": "651020ba30ca4c96cf97f5ba19828605", "testCaseId": "173584f58b43201f68b14a2421a0b95b", "fullName": "test_div_fail[0ä½ä¸ºé¤æ°]#test_div_fail", "labels": [{"name": "story", "value": "除法功能"}, {"name": "feature", "value": "计算器"}, {"name": "suite", "value": "test_div_fail[0ä½ä¸ºé¤æ°]"}, {"name": "host", "value": "liuyaodeiMac.local"}, {"name": "thread", "value": "10871-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_div_fail[0ä½ä¸ºé¤æ°]"}]}